### ISSUE TITLE
You can group styles together

### ISSUE THREAD

**Issue by treyeckels** [aJentD/Basic-Portfolio#5]
https://github.com/aJentD/Basic-Portfolio/blob/72ab1f2a84709f0ae9ab4a8d496122aaebfad746/assets/css/style.css#L25

This is just a tip for organization - you can group styling together like below. Then if the designer or client decides to change the font family (for example in this case), there's just 1 style rule to update.

```css
#discription,
#name {
  font-family: 'Georgia'
}
```
